apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: codegen1-may7-2
  janus-idp.io/tekton: codegen1-may7-2
  backstage.io/kubernetes-id: codegen1-may7-2
  backstage.io/kubernetes-namespace: codegen1-may7-2
  app.kubernetes.io/part-of: codegen1-may7-2
resources:
  - application-dev.yaml