apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: codegen1-may7-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: codegen1-may7-2
  name: codegen1-may7-2
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
