kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: codegen1-may7-2-imagestream-job-rolebinding
  namespace: redhat-ods-applications
subjects:
  - kind: ServiceAccount
    name: codegen1-may7-2-dsp-job
    namespace: codegen1-may7-2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: codegen1-may7-2-imagestream-job-role
